# Generated by Django 6.0.2 on 2026-02-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo_electronico', models.CharField(max_length=150, unique=True)),
                ('puesto_institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('resumen_profesional', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos Generales',
                'verbose_name_plural': 'Datos Generales',
                'db_table': 'datos_generales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('admin', 'Administrador')], default='profesor', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario Portal',
                'verbose_name_plural': 'Usuarios Portal',
                'db_table': 'usuarios_portal',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_capacitacion', models.CharField(blank=True, max_length=200, null=True)),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actualizacion', models.CharField(max_length=300)),
                ('tipo_actualizacion', models.CharField(blank=True, max_length=200, null=True)),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Actualización',
                'verbose_name_plural': 'Actualizaciones',
                'db_table': 'actualizacion',
            },
        ),
        migrations.CreateModel(
            name='EstudioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_estudio', models.CharField(max_length=300)),
                ('nivel_estudios', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='estudios_academicos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Estudio Académico',
                'verbose_name_plural': 'Estudios Académicos',
                'db_table': 'estudios_academicos',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_puesto', models.CharField(max_length=300)),
                ('organizacion_empresa', models.CharField(blank=True, max_length=300, null=True)),
                ('inicio_mes_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_mes_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencia Laboral',
                'db_table': 'experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='LogroProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_logro', models.TextField()),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='logros_profesionales', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Logro Profesional',
                'verbose_name_plural': 'Logros Profesionales',
                'db_table': 'logros_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organismo', models.CharField(max_length=300)),
                ('anio_inicio', models.IntegerField(blank=True, null=True)),
                ('anio_fin', models.IntegerField(blank=True, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='organismos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'db_table': 'organismos',
            },
        ),
        migrations.CreateModel(
            name='PremioDistincion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_premio', models.TextField()),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='premios_distinciones', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Premio o Distinción',
                'verbose_name_plural': 'Premios y Distinciones',
                'db_table': 'premios_distinciones',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_publicacion', models.TextField(blank=True, null=True)),
                ('anio_producto', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
                'db_table': 'productos_academicos',
            },
        ),
    ]
