# Generated by Django 6.0.2 on 2026-02-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_capacitacion', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Capacitación',
                'verbose_name_plural': 'Catálogo de Capacitación',
                'db_table': 'catalogo_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='CatalogoCarrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=300)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Catálogo de Carreras',
                'db_table': 'catalogo_carreras',
            },
        ),
        migrations.CreateModel(
            name='CatalogoExperienciaLaboral',
            fields=[
                ('id_tipo_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_experiencia', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Experiencia Laboral',
                'verbose_name_plural': 'Catálogo de Experiencia Laboral',
                'db_table': 'catalogo_experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='CatalogoInstitucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=300)),
                ('activo', models.PositiveSmallIntegerField(default=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Catálogo de Instituciones',
                'db_table': 'catalogo_instituciones',
            },
        ),
        migrations.CreateModel(
            name='CatalogoInstitucionEducativa',
            fields=[
                ('id_institucion_educativa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=300)),
                ('activo', models.PositiveSmallIntegerField(default=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Catálogo de Instituciones Educativas',
                'db_table': 'catalogo_instituciones_educativas',
            },
        ),
        migrations.CreateModel(
            name='CatalogoNivelEstudio',
            fields=[
                ('id_nivel_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('desc_nivel_estudio', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nivel de Estudio',
                'verbose_name_plural': 'Catálogo de Nivel de Estudio',
                'db_table': 'catalogo_nivel_estudio',
            },
        ),
        migrations.CreateModel(
            name='CatalogoOrganismo',
            fields=[
                ('id_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_organismo', models.CharField(max_length=300)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Catálogo de Organismos',
                'db_table': 'catalogo_organismos',
            },
        ),
        migrations.CreateModel(
            name='CatalogoPais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=150)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Catálogo de Países',
                'db_table': 'catalogo_paises',
            },
        ),
        migrations.CreateModel(
            name='CatalogoPuestoInstitucional',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('desc_puesto', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Puesto Institucional',
                'verbose_name_plural': 'Catálogo de Puesto Institucional',
                'db_table': 'catalogo_puesto_institucional',
            },
        ),
        migrations.CreateModel(
            name='CatalogoTipoCurso',
            fields=[
                ('id_tipo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_curso', models.CharField(max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Curso',
                'verbose_name_plural': 'Catálogo de Tipo de Curso',
                'db_table': 'catalogo_tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id_profesor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('puesto_institucional', models.CharField(blank=True, max_length=200, null=True)),
                ('resumen_profesional', models.TextField(blank=True, null=True)),
                ('activo', models.PositiveSmallIntegerField(default=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos Generales',
                'verbose_name_plural': 'Datos Generales',
                'db_table': 'datos_generales',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(max_length=300)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_capacitacion', models.ForeignKey(blank=True, db_column='id_tipo_capacitacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogocapacitacion')),
                ('institucion_educativa', models.ForeignKey(blank=True, db_column='id_institucion_educativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucioneducativa')),
                ('tipo_curso', models.ForeignKey(blank=True, db_column='id_tipo_curso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogotipocurso')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='capacitacion_actualizacion', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Capacitación / Actualización',
                'verbose_name_plural': 'Capacitación / Actualización',
                'db_table': 'capacitacion_actualizacion',
            },
        ),
        migrations.CreateModel(
            name='EstudioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_estudio', models.CharField(max_length=300)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion_educativa', models.ForeignKey(blank=True, db_column='id_institucion_educativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucioneducativa')),
                ('nivel_estudio', models.ForeignKey(blank=True, db_column='id_nivel_estudio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogonivelestudio')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='estudios_academicos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Estudio Académico',
                'verbose_name_plural': 'Estudios Académicos',
                'db_table': 'estudios_academicos',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_puesto', models.CharField(max_length=300)),
                ('inicio_mes_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('fin_mes_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='experiencia_laboral', to='api.datosgenerales')),
                ('tipo_experiencia', models.ForeignKey(blank=True, db_column='id_tipo_experiencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoexperiencialaboral')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencia Laboral',
                'db_table': 'experiencia_laboral',
            },
        ),
        migrations.CreateModel(
            name='GestionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=200, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('admin', 'Administrador')], default='profesor', max_length=50)),
                ('activo', models.PositiveSmallIntegerField(default=1)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(blank=True, db_column='id_profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Gestión de Usuarios',
                'db_table': 'gestion_usuarios',
            },
        ),
        migrations.CreateModel(
            name='LogroProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_logro', models.TextField()),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion', models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='logros_profesionales', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Logro Profesional',
                'verbose_name_plural': 'Logros Profesionales',
                'db_table': 'logros_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_inicio', models.IntegerField(blank=True, null=True)),
                ('anio_fin', models.IntegerField(blank=True, null=True)),
                ('nivel_experiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('organismo', models.ForeignKey(blank=True, db_column='id_organismo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoorganismo')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='organismos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'db_table': 'organismos',
            },
        ),
        migrations.CreateModel(
            name='PremioDistincion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_premio', models.TextField()),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='premios_distinciones', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Premio o Distinción',
                'verbose_name_plural': 'Premios y Distinciones',
                'db_table': 'premios_distinciones',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto_academico', models.TextField(blank=True, null=True)),
                ('anio_producto', models.IntegerField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('institucion_educativa', models.ForeignKey(blank=True, db_column='id_institucion_educativa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucioneducativa')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='api.datosgenerales')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': 'Productos Académicos',
                'db_table': 'productos_academicos',
            },
        ),
    ]
