# Generated by Django 6.0.2 on 2026-02-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capacitacion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_capacitacion', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_obtencion', models.IntegerField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('tip_tipo_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacitación / Actualización',
                'verbose_name_plural': 'Capacitación / Actualización',
                'db_table': 'capacitacion_actualizacion',
            },
        ),
        migrations.CreateModel(
            name='CatalogoInstitucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=300)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Catálogo de Instituciones',
                'db_table': 'catalogo_instituciones',
            },
        ),
        migrations.CreateModel(
            name='GestionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('admin', 'Administrador')], default='profesor', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Gestión de Usuarios',
                'db_table': 'gestion_usuarios',
            },
        ),
        migrations.RemoveField(
            model_name='actualizacion',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='UsuarioPortal',
        ),
        migrations.RenameField(
            model_name='estudioacademico',
            old_name='nivel_estudios',
            new_name='nivel_estudio',
        ),
        migrations.RemoveField(
            model_name='datosgenerales',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='organizacion_empresa',
        ),
        migrations.RemoveField(
            model_name='organismo',
            name='organismo',
        ),
        migrations.AddField(
            model_name='capacitacionactualizacion',
            name='profesor',
            field=models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, related_name='capacitacion_actualizacion', to='api.datosgenerales'),
        ),
        migrations.AddField(
            model_name='capacitacionactualizacion',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AddField(
            model_name='organismo',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AlterField(
            model_name='estudioacademico',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AlterField(
            model_name='logroprofesional',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AlterField(
            model_name='premiodistincion',
            name='institucion',
            field=models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogoinstitucion'),
        ),
        migrations.AddField(
            model_name='gestionusuario',
            name='profesor',
            field=models.ForeignKey(blank=True, db_column='id_profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='api.datosgenerales'),
        ),
        migrations.DeleteModel(
            name='Actualizacion',
        ),
        migrations.DeleteModel(
            name='Capacitacion',
        ),
    ]
